import { toDms, normalizeBearing, calculateF3AZone } from "./geoUtils.js";

export function getViewportCorners(map) {
    if (!map) return null;

    const rect = map.getCanvas().getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;

    if (!width || !height) return null;

    const topLeft = map.unproject([0, 0]);
    const topRight = map.unproject([width, 0]);
    const bottomLeft = map.unproject([0, height]);
    const bottomRight = map.unproject([width, height]);

    return { topLeft, topRight, bottomLeft, bottomRight };
}

function resolveExportCorners(corners, bounds) {
    return {
        topLeft: {
            lat: Number((corners?.topLeft.lat ?? bounds.north).toFixed(8)),
            lon: Number((corners?.topLeft.lng ?? bounds.west).toFixed(8)),
        },
        topRight: {
            lat: Number((corners?.topRight.lat ?? bounds.north).toFixed(8)),
            lon: Number((corners?.topRight.lng ?? bounds.east).toFixed(8)),
        },
        bottomLeft: {
            lat: Number((corners?.bottomLeft.lat ?? bounds.south).toFixed(8)),
            lon: Number((corners?.bottomLeft.lng ?? bounds.west).toFixed(8)),
        },
        bottomRight: {
            lat: Number((corners?.bottomRight.lat ?? bounds.south).toFixed(8)),
            lon: Number((corners?.bottomRight.lng ?? bounds.east).toFixed(8)),
        },
    };
}

function toLuaGeoPoint(point) {
    const lat = Number(point.lat.toFixed(8));
    const lon = Number(point.lng.toFixed(8));
    return `{ lat = ${lat}, lon = ${lon} }`;
}

function hexToRgbLua(hex) {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return `{ r = ${r}, g = ${g}, b = ${b} }`;
}

function rgbToHex(r, g, b) {
    return '#' + [r, g, b].map(v => Math.max(0, Math.min(255, v)).toString(16).padStart(2, '0')).join('');
}

export function createJsonBlob({ map, bounds, rotation }) {
    const corners = getViewportCorners(map);
    const payload = {
        ...resolveExportCorners(corners, bounds),
        rotation: Number(rotation.toFixed(1)),
    };

    return new Blob([JSON.stringify(payload, null, 2)], {
        type: "application/json",
    });
}

export function createLuaBlob({
    map,
    bounds,
    rotation,
    zoom,
    mapTitle,
    mapWidth,
    mapHeight,
    mapType,
    center,
    homePosition,
    f3aZoneVisible,
    f3aRotation,
    f3aBaseDistance,
    f3aColor,
}) {
    const corners = getViewportCorners(map);
    const { topLeft, topRight, bottomLeft, bottomRight } = resolveExportCorners(
        corners,
        bounds,
    );


    let f3aZoneLua = "nil";
    if (homePosition) {
        const { apex: apexGeo, left: leftGeo, right: rightGeo } = calculateF3AZone(
            homePosition,
            f3aRotation,
            f3aBaseDistance,
        );
        const axisBearing = normalizeBearing(Number(f3aRotation) || 0);

        f3aZoneLua = `{ visible = ${Boolean(f3aZoneVisible)}, rotation = ${Number(axisBearing.toFixed(1))}, baseDistance = ${Number(Number(f3aBaseDistance || 150).toFixed(1))}, apex = ${toLuaGeoPoint(apexGeo)}, left = ${toLuaGeoPoint(leftGeo)}, right = ${toLuaGeoPoint(rightGeo)} }`;
    }

    const colorLua = f3aColor && /^#[0-9a-fA-F]{6}$/.test(f3aColor)
        ? hexToRgbLua(f3aColor)
        : '{ r = 255, g = 255, b = 255 }';
    const centerLat = center ? Number(center.lat.toFixed(8)) : 0;
    const centerLng = center ? Number(center.lng.toFixed(8)) : 0;
    const homePositionLua = homePosition
        ? `{ lat = ${Number(homePosition.lat.toFixed(8))}, lng = ${Number(homePosition.lng.toFixed(8))} }`
        : 'nil';

    const lines = [
        `-- MAP DATA GENERATED BY ETHOS GPS MAP GENERATOR`,
        `-- generated at ${new Date().toISOString()}`,
        `-- this file should be place in the same directory as the bitmap for the map`,
        `--`,
        `return {`,
        `  title = "${mapTitle}",`,
        `  resolution = { width = ${mapWidth}, height = ${mapHeight} },`,
        `  zoom = ${Number(zoom.toFixed(1))},`,
        `  rotation = ${Number(rotation.toFixed(1))},`,
        `  mapType = "${mapType ?? 'y'}",`,
        `  center = { lat = ${centerLat}, lng = ${centerLng} },`,
        `  homePosition = ${homePositionLua},`,
        `  f3aZone = ${f3aZoneLua},`,
        `  f3aColor = ${colorLua},`,
        `  topLeft = { lat = ${topLeft.lat}, lon = ${topLeft.lon} },`,
        `  topRight = { lat = ${topRight.lat}, lon = ${topRight.lon} },`,
        `  bottomLeft = { lat = ${bottomLeft.lat}, lon = ${bottomLeft.lon} },`,
        `  bottomRight = { lat = ${bottomRight.lat}, lon = ${bottomRight.lon} },`,
        `}`,
        ...(rotation === 0 ? [
        "--",
        "-- You can also use the associated bmp image directly in Ethos GPS Map Widget",
        "-- ETHOS GPS MAP WIDGET SETTINGS",
        "--------------------------------",
        `-- Latitude: ${toDms(topLeft.lat, true)} - ${toDms(bottomRight.lat, true)}`,
        `-- Longitude: ${toDms(bottomRight.lon, false)} - ${toDms(topLeft.lon, false)}`,
        ] : []),
    ];

    return new Blob([lines.join("\n")], { type: "text/plain" });
}

/**
 * Parse a Lua map file generated by this tool back into a project object
 * compatible with handleLoadProject in App.svelte.
 * Returns null if the file cannot be recognised.
 */
export function parseLuaProject(text) {
    // Isolate the f3aZone line first so its nested field names
    // (rotation, lat, lon…) don't confuse the top-level parsers.
    const f3aLineMatch = text.match(/f3aZone\s*=\s*([^\n]+)/);
    const f3aStr = f3aLineMatch?.[1]?.trim() ?? '';
    const body = f3aLineMatch ? text.replace(f3aLineMatch[0], '') : text;

    const num = (re, src = body) => { const m = src.match(re); return m ? Number(m[1]) : null; };
    const str = (re, src = body) => { const m = src.match(re); return m ? m[1] : null; };

    const title      = str(/title\s*=\s*"([^"]+)"/);
    const width      = num(/resolution\s*=\s*\{[^}]*width\s*=\s*(\d+)/);
    const height     = num(/resolution\s*=\s*\{[^}]*height\s*=\s*(\d+)/);
    const zoom       = num(/\bzoom\s*=\s*([\d.]+)/);
    const rotation   = num(/\brotation\s*=\s*([-\d.]+)/);
    const mapType    = str(/\bmapType\s*=\s*"([^"]+)"/);

    const centerMatch = body.match(/\bcenter\s*=\s*\{\s*lat\s*=\s*([\d.-]+)\s*,\s*lng\s*=\s*([\d.-]+)/);
    const parsedCenter = centerMatch
        ? { lat: Number(centerMatch[1]), lng: Number(centerMatch[2]) }
        : null;

    const colorMatch = body.match(/\bf3aColor\s*=\s*\{\s*r\s*=\s*(\d+)\s*,\s*g\s*=\s*(\d+)\s*,\s*b\s*=\s*(\d+)/);
    const f3aColor = colorMatch
        ? rgbToHex(Number(colorMatch[1]), Number(colorMatch[2]), Number(colorMatch[3]))
        : '#ffffff';

    const homePosMatch = body.match(/\bhomePosition\s*=\s*\{\s*lat\s*=\s*([\d.-]+)\s*,\s*lng\s*=\s*([\d.-]+)/);
    const explicitHomePosition = homePosMatch
        ? { lat: Number(homePosMatch[1]), lng: Number(homePosMatch[2]) }
        : null;

    const parseCorner = (name) => {
        const m = body.match(new RegExp(name + '\\s*=\\s*\\{\\s*lat\\s*=\\s*([\\d.-]+)\\s*,\\s*lon\\s*=\\s*([\\d.-]+)'));
        return m ? { lat: Number(m[1]), lon: Number(m[2]) } : null;
    };

    const topLeft     = parseCorner('topLeft');
    const topRight    = parseCorner('topRight');
    const bottomLeft  = parseCorner('bottomLeft');
    const bottomRight = parseCorner('bottomRight');

    if (!title || zoom == null || rotation == null || !topLeft || !topRight || !bottomLeft || !bottomRight) {
        return null;
    }

    // f3aZone
    let f3aZoneVisible = false, f3aRotation = 0, f3aBaseDistance = 150;
    let apexHomePosition = null;
    if (f3aStr && !f3aStr.startsWith('nil')) {
        f3aZoneVisible = /visible\s*=\s*true/.test(f3aStr);
        const fRot  = f3aStr.match(/\brotation\s*=\s*([-\d.]+)/);
        const fBase = f3aStr.match(/baseDistance\s*=\s*([\d.]+)/);
        f3aRotation     = fRot  ? Number(fRot[1])  : 0;
        f3aBaseDistance = fBase ? Number(fBase[1]) : 150;

        // Fallback: recover home position from the f3a apex for older files
        const apexMatch = f3aStr.match(/apex\s*=\s*\{\s*lat\s*=\s*([\d.-]+)\s*,\s*lon\s*=\s*([\d.-]+)/);
        if (apexMatch) {
            apexHomePosition = { lat: Number(apexMatch[1]), lng: Number(apexMatch[2]) };
        }
    }
    // Prefer the explicit homePosition field; fall back to apex for older files
    const homePosition = explicitHomePosition ?? apexHomePosition;

    // Map width×height back to a known resolution key or fall through to custom
    const knownResolutions = ['800,480', '784,316', '480,320'];
    const resKey = `${width},${height}`;
    const resolution = knownResolutions.includes(resKey) ? resKey : 'custom';

    // Centre: use explicit value if present, fall back to mean of four corners
    let center;
    if (parsedCenter) {
        center = parsedCenter;
    } else {
        const allCorners = [topLeft, topRight, bottomLeft, bottomRight];
        center = {
            lat: allCorners.reduce((s, c) => s + c.lat, 0) / 4,
            lng: allCorners.reduce((s, c) => s + c.lon, 0) / 4,
        };
    }

    return {
        mapTitle: title,
        name: title,
        resolution,
        customW: width  ?? 800,
        customH: height ?? 480,
        mapType: mapType ?? 'y',
        zoomLock: false,
        rotation,
        zoom,
        center,
        homePosition,
        f3aZoneVisible,
        f3aRotation,
        f3aBaseDistance,
        f3aColor,
    };
}

export function createMetadataBlob({
    map,
    bounds,
    rotation,
    zoom,
    mapTitle,
    mapWidth,
    mapHeight,
}) {
    const corners = getViewportCorners(map);
    const { topLeft, topRight, bottomLeft, bottomRight } = resolveExportCorners(
        corners,
        bounds,
    );

    const lines = [
        `MAP METADATA: ${mapTitle}`,
        `Generated: ${new Date().toLocaleString()}`,
        `Resolution: ${mapWidth} x ${mapHeight} pixels`,
        `Zoom: ${zoom.toFixed(1)}`,
        `Rotation: ${rotation.toFixed(1)} degrees`,
        "",
        "CORNERS (Decimal)",
        "-----------------",
        `Top Left:     lat ${topLeft.lat.toFixed(8)}, lon ${topLeft.lon.toFixed(8)}`,
        `Top Right:    lat ${topRight.lat.toFixed(8)}, lon ${topRight.lon.toFixed(8)}`,
        `Bottom Left:  lat ${bottomLeft.lat.toFixed(8)}, lon ${bottomLeft.lon.toFixed(8)}`,
        `Bottom Right: lat ${bottomRight.lat.toFixed(8)}, lon ${bottomRight.lon.toFixed(8)}`,
        "",
        "CORNERS (DMS)",
        "-------------",
        `Top Left:     ${toDms(topLeft.lat, true)} | ${toDms(topLeft.lon, false)}`,
        `Top Right:    ${toDms(topRight.lat, true)} | ${toDms(topRight.lon, false)}`,
        `Bottom Left:  ${toDms(bottomLeft.lat, true)} | ${toDms(bottomLeft.lon, false)}`,
        `Bottom Right: ${toDms(bottomRight.lat, true)} | ${toDms(bottomRight.lon, false)}`,
        ...(rotation === 0 ? [
        "",
        "ETHOS GPS MAP WIDGET SETTINGS",
        "------------------------------",
        `Latitude: ${toDms(topLeft.lat, true)} - ${toDms(bottomRight.lat, true)}`,
        `Longitude: ${toDms(bottomRight.lon, false)} - ${toDms(topLeft.lon, false)}`,
        ] : [
            "",
            "NOTE: This map is not compatible with the Ethos GPS Map Widget",
        ]),
    ];

    return new Blob([lines.join("\n")], { type: "text/plain" });
}
