import { toDms, normalizeBearing, destinationPoint, calculateF3AZone } from "./geoUtils.js";

export function getViewportCorners(map) {
    if (!map) return null;

    const rect = map.getCanvas().getBoundingClientRect();
    const width = rect.width;
    const height = rect.height;

    if (!width || !height) return null;

    const topLeft = map.unproject([0, 0]);
    const topRight = map.unproject([width, 0]);
    const bottomLeft = map.unproject([0, height]);
    const bottomRight = map.unproject([width, height]);

    return { topLeft, topRight, bottomLeft, bottomRight };
}

function resolveExportCorners(corners, bounds) {
    return {
        topLeft: {
            lat: Number((corners?.topLeft.lat ?? bounds.north).toFixed(8)),
            lon: Number((corners?.topLeft.lng ?? bounds.west).toFixed(8)),
        },
        topRight: {
            lat: Number((corners?.topRight.lat ?? bounds.north).toFixed(8)),
            lon: Number((corners?.topRight.lng ?? bounds.east).toFixed(8)),
        },
        bottomLeft: {
            lat: Number((corners?.bottomLeft.lat ?? bounds.south).toFixed(8)),
            lon: Number((corners?.bottomLeft.lng ?? bounds.west).toFixed(8)),
        },
        bottomRight: {
            lat: Number((corners?.bottomRight.lat ?? bounds.south).toFixed(8)),
            lon: Number((corners?.bottomRight.lng ?? bounds.east).toFixed(8)),
        },
    };
}

function toLuaGeoPoint(point) {
    const lat = Number(point.lat.toFixed(8));
    const lon = Number(point.lng.toFixed(8));
    return `{ lat = ${lat}, lon = ${lon} }`;
}

export function createJsonBlob({ map, bounds, rotation }) {
    const corners = getViewportCorners(map);
    const payload = {
        ...resolveExportCorners(corners, bounds),
        rotation: Number(rotation.toFixed(1)),
    };

    return new Blob([JSON.stringify(payload, null, 2)], {
        type: "application/json",
    });
}

export function createLuaBlob({
    map,
    bounds,
    rotation,
    zoom,
    mapTitle,
    mapWidth,
    mapHeight,
    homePosition,
    f3aZoneVisible,
    f3aRotation,
    f3aBaseDistance,
}) {
    const corners = getViewportCorners(map);
    const { topLeft, topRight, bottomLeft, bottomRight } = resolveExportCorners(
        corners,
        bounds,
    );

    const homeLua = homePosition
        ? toLuaGeoPoint({ lat: homePosition.lat, lng: homePosition.lng })
        : "nil";

    let f3aZoneLua = "nil";
    if (homePosition) {
        const { apex: apexGeo, left: leftGeo, right: rightGeo } = calculateF3AZone(
            homePosition,
            f3aRotation,
            f3aBaseDistance,
        );
        const axisBearing = normalizeBearing(Number(f3aRotation) || 0);

        f3aZoneLua = `{ visible = ${Boolean(f3aZoneVisible)}, rotation = ${Number(axisBearing.toFixed(1))}, baseDistance = ${Number(Number(f3aBaseDistance || 150).toFixed(1))}, apex = ${toLuaGeoPoint(apexGeo)}, left = ${toLuaGeoPoint(leftGeo)}, right = ${toLuaGeoPoint(rightGeo)} }`;
    }

    const lua = `
    -- MAP DATA GENERATED BY ETHOS GPS MAP GENERATOR
    -- generated at ${new Date().toISOString()}
    -- this file should be place in the same directory as the bitmap for the map
    --
    return {
  title = "${mapTitle}",
  resolution = { width = ${mapWidth}, height = ${mapHeight} },
  zoom = ${Number(zoom.toFixed(1))},
  rotation = ${Number(rotation.toFixed(1))},
  f3aZone = ${f3aZoneLua},
  topLeft = { lat = ${topLeft.lat}, lon = ${topLeft.lon} },
  topRight = { lat = ${topRight.lat}, lon = ${topRight.lon} },
  bottomLeft = { lat = ${bottomLeft.lat}, lon = ${bottomLeft.lon} },
  bottomRight = { lat = ${bottomRight.lat}, lon = ${bottomRight.lon} }
}\n`;

    return new Blob([lua], { type: "text/plain" });
}

export function createMetadataBlob({
    map,
    bounds,
    rotation,
    zoom,
    mapTitle,
    mapWidth,
    mapHeight,
}) {
    const corners = getViewportCorners(map);
    const { topLeft, topRight, bottomLeft, bottomRight } = resolveExportCorners(
        corners,
        bounds,
    );

    const lines = [
        `MAP METADATA: ${mapTitle}`,
        `Generated: ${new Date().toLocaleString()}`,
        `Resolution: ${mapWidth} x ${mapHeight} pixels`,
        `Zoom: ${zoom.toFixed(1)}`,
        `Rotation: ${rotation.toFixed(1)} degrees`,
        "",
        "CORNERS (Decimal)",
        "-----------------",
        `Top Left:     lat ${topLeft.lat.toFixed(8)}, lon ${topLeft.lon.toFixed(8)}`,
        `Top Right:    lat ${topRight.lat.toFixed(8)}, lon ${topRight.lon.toFixed(8)}`,
        `Bottom Left:  lat ${bottomLeft.lat.toFixed(8)}, lon ${bottomLeft.lon.toFixed(8)}`,
        `Bottom Right: lat ${bottomRight.lat.toFixed(8)}, lon ${bottomRight.lon.toFixed(8)}`,
        "",
        "CORNERS (DMS)",
        "-------------",
        `Top Left:     ${toDms(topLeft.lat, true)} | ${toDms(topLeft.lon, false)}`,
        `Top Right:    ${toDms(topRight.lat, true)} | ${toDms(topRight.lon, false)}`,
        `Bottom Left:  ${toDms(bottomLeft.lat, true)} | ${toDms(bottomLeft.lon, false)}`,
        `Bottom Right: ${toDms(bottomRight.lat, true)} | ${toDms(bottomRight.lon, false)}`,
        ...(rotation === 0 ? [
        "",
        "ETHOS GPS MAP WIDGET SETTINGS",
        "------------------------------",
        `Latitude: ${toDms(topLeft.lat, true)} - ${toDms(bottomRight.lat, true)}`,
        `Longitude: ${toDms(bottomRight.lon, false)} - ${toDms(topLeft.lon, false)}`,
        ] : [
            "",
            "NOTE: This map is not compatible with the Ethos GPS Map Widget",
        ]),
    ];

    return new Blob([lines.join("\n")], { type: "text/plain" });
}
